version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: build-test
    displayName: build-test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: build
        gccVersion: '9.4'
        commands:
          - mkdir build
          - ''
          - make test-output
          - ''
          - make save-test-results
        artifacts:
          - name: test_results
            path:
              - ./build/test_results.json
        caches: []
        notify: []
        strategy:
          retry: '0'
  - name: pull
    displayName: pull
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: test_results
        artifactName: output
        notify: []
        strategy:
          retry: '0'
  - name: post
    displayName: post
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: test
          hostID:
            - ed27f715-e7c7-47c8-9a9a-a1535e12e5c7
        deployArtifact:
          - source: artifact
            name: output
            target: ~/gitee_go/deploy
            dependArtifact: test_results
            artifactRepository: default
            artifactName: output
            artifactVersion: latest
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - mkdir -p /home/xukunyuan/app
          - tar zxvf ~/gitee_go/deploy/output.tar.gz -C /home/xukunyuan/app
          - '# sh /home/admin/app/deploy.sh restart'
          - '# 如果你是php之类的无需制品包的制品方式，可以使用 git clone 或者 git pull 将源代码更新到服务器，再执行其他命令'
          - '# git clone ***@***.git'
          - echo 'Hello Gitee Go!'
        notify: []
        strategy:
          retry: '0'
